services:
  app:
    build: ./
    ports: 
      -"3000:3000"
    
  depends_on:
    -db
  volumes:
    -.:/app
  
  
  mailhog:
    image: mailhog/mailhog
    ports:
      -"1025:1025"
      -"8025:8025"

  db:
  image: postgress:12
  environment:
   POSTGRES_USER: postgress
   POSTGRES_PASSWORD: postgress
   POSTGRES_DB: postgress